### ISSUE TITLE
red alart after enabled the convai ext

### ISSUE THREAD

**Issue by l3ytao** [Conv-AI/ov_extension#1]
After added the absolute path to the exts folder and enabled the convai ext,  convai  window  didn't appear  and there is no convai option in [Window] menu. There is a red alart sideby the enabled switch but no information showed while hovering. 
![12232](https://github.com/Conv-AI/ov_extension/assets/117420392/299f443f-265a-4cad-bbc3-e6f4ecad8a17)

**Comment by eyew28** [comment]
I don't see this issue with Create 2022.3.3 but am seeing this issue too with USD Composer 2023.1.0 beta

**Comment by MohamedEshmawy** [comment]
We just made an update to the extension (1.0.3) and we added new installation steps that might solve any previous errors

**Comment by gschian0** [comment]
these are my errors with the same issue... I downloaded the repo and pointed to it... now it looks like you can install it from the third party without using the downloaded repo .. 
`2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer] Failed to import python module convai. Error: cannot import name 'builder' from 'google.protobuf.internal' (c:\users\gennaroschiano\appdata\local\ov\pkg\machinima-2022.3.0\extscache\omni.audio2face.player_deps-104.7.0+104.1.wx64\deps\py\google\protobuf\internal\__init__.py). Traceback:
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer] Traceback (most recent call last):
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]   File "c:/users/gennaroschiano/appdata/local/ov/pkg/machinima-2022.3.0/kit/kernel/py\omni\ext\_impl\custom_importer.py", line 76, in import_module
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]     return importlib.import_module(name)
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]   File "c:\users\gennaroschiano\appdata\local\ov\pkg\machinima-2022.3.0\kit\python\lib\importlib\__init__.py", line 127, in import_module
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]   File "c:\users\gennaroschiano\appdata\local\ov\data\kit\machinima\2022.3\exts\3\convai-1.0.3\convai\__init__.py", line 1, in <module>
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]     from .extension import *
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]   File "c:\users\gennaroschiano\appdata\local\ov\data\kit\machinima\2022.3\exts\3\convai-1.0.3\convai\extension.py", line 10, in <module>
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]     from .rpc import service_pb2 as convai_service_msg
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]   File "c:\users\gennaroschiano\appdata\local\ov\data\kit\machinima\2022.3\exts\3\convai-1.0.3\convai\rpc\service_pb2.py", line 5, in <module>
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer]     from google.protobuf.internal import builder as _builder
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer] ImportError: cannot import name 'builder' from 'google.protobuf.internal' (c:\users\gennaroschiano\appdata\local\ov\pkg\machinima-2022.3.0\extscache\omni.audio2face.player_deps-104.7.0+104.1.wx64\deps\py\google\protobuf\internal\__init__.py)
2024-07-13 16:04:15  [Error] [omni.ext._impl.custom_importer] 
2024-07-13 16:04:15  [Error] [carb.scripting-python.plugin] Exception: Extension python module: 'convai' in 'c:\users\gennaroschiano\appdata\local\ov\data\kit\machinima\2022.3\exts\3\convai-1.0.3' failed to load.
2024-07-13 16:04:15  [Error] [carb.scripting-python.plugin] 
2024-07-13 16:04:15  [Error] [carb.scripting-python.plugin] At:
2024-07-13 16:04:15  [Error] [carb.scripting-python.plugin]   c:/users/gennaroschiano/appdata/local/ov/pkg/machinima-2022.3.0/kit/kernel/py\omni\ext\_impl\_internal.py(188): startup
2024-07-13 16:04:15  [Error] [carb.scripting-python.plugin]   c:/users/gennaroschiano/appdata/local/ov/pkg/machinima-2022.3.0/kit/kernel/py\omni\ext\_impl\_internal.py(280): startup_extension
2024-07-13 16:04:15  [Error] [carb.scripting-python.plugin]   PythonExtension.cpp::startup()(2): <module>
2024-07-13 16:04:15  [Error] [carb.scripting-python.plugin] 
2024-07-13 16:04:15  [Error] [omni.ext.plugin] [ext: convai-1.0.3] Failed to startup python extension.
`
any help would be appreciated ....
